default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: business_tracker_development
  pool: 5
  username: von
  password: kms316
  host: localhost
  port: 5432

test: &test
  <<: *default
  database: business_tracker_test
  pool: 5
  username: von
  password: kms316
  host: localhost
  port: 5432


production:
  <<: *default
  database: business_tracker_production
  pool: 5
  username: von
  password: kms316
  host: localhost
  port: 5432
